Metrics/LineLength:
  Max: 200

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false
    

  inherit_gem:
  rubocop-rails_config:
    - config/rails.yml