--- 
Metrics: 
  Enabled: false
Metrics/LineLength: 
  Max: 200
Style/ClassAndModuleChildren: 
  Enabled: false
Style/CommentedKeyword: 
  Enabled: false
Style/Documentation: 
  Enabled: false
Style/FrozenStringLiteralComment: 
  Enabled: false
Style/IfUnlessModifier: 
  Enabled: false
Style/StringLiterals: 
  Enabled: false
inherit_gem: 
  ragnarson-stylecheck: 
    - config/rubocop.yml
  rubocop-rails_config: 
    - config/rails.yml